[project]
name = "github-scraper"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = [
  "aiochclient>=2.6.0",
  "aiohttp>=3.11.11",
  "aiolimiter>=1.2.1",
  "certifi>=2025.1.31",
  "pydantic>=2.10.6",
  "tenacity>=9.0.0",
]
