services:
  web:
    depends_on:
      - postgres
    build: .
    env_file: ".env"
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./uv.lock
  postgres:
    image: postgres:16.8
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    expose:
      - "5432"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

volumes:
  postgres-data:
